--  Configuration for light_tasking_rp2350 generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Light_Tasking_Rp2350_Config is
   pragma Pure;

   Crate_Version : constant String := "15.4.0";
   Crate_Name : constant String := "light_tasking_rp2350";

   Alire_Host_OS : constant String := "macos";

   Alire_Host_Arch : constant String := "aarch64";

   Alire_Host_Distro : constant String := "homebrew";

   Max_CPUs_First : constant :=  1;
   Max_CPUs_Last : constant :=  2;
   Max_CPUs : constant :=  2;

   PLL_USB_VCO_Multiple_First : constant :=  16;
   PLL_USB_VCO_Multiple_Last : constant :=  320;
   PLL_USB_VCO_Multiple : constant :=  40;

   Interrupt_Secondary_Stack_Size_First : constant :=  1;
   Interrupt_Secondary_Stack_Size_Last : constant :=  9223372036854775807;
   Interrupt_Secondary_Stack_Size : constant :=  128;

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := release;

   PLL_Sys_VCO_Multiple_First : constant :=  16;
   PLL_Sys_VCO_Multiple_Last : constant :=  320;
   PLL_Sys_VCO_Multiple : constant :=  125;

   PLL_USB_Post_Div_1_First : constant :=  1;
   PLL_USB_Post_Div_1_Last : constant :=  7;
   PLL_USB_Post_Div_1 : constant :=  5;

   PLL_USB_Post_Div_2_First : constant :=  1;
   PLL_USB_Post_Div_2_Last : constant :=  7;
   PLL_USB_Post_Div_2 : constant :=  2;

   PLL_USB_Reference_Div_First : constant :=  1;
   PLL_USB_Reference_Div_Last : constant :=  63;
   PLL_USB_Reference_Div : constant :=  1;

   XOSC_Frequency_First : constant :=  0;
   XOSC_Frequency_Last : constant :=  9223372036854775807;
   XOSC_Frequency : constant :=  12000000;

   Flash_Size_First : constant :=  2;
   Flash_Size_Last : constant :=  16;
   Flash_Size : constant :=  2;

   Interrupt_Stack_Size_First : constant :=  1;
   Interrupt_Stack_Size_Last : constant :=  9223372036854775807;
   Interrupt_Stack_Size : constant :=  1024;

   PLL_Sys_Reference_Div_First : constant :=  1;
   PLL_Sys_Reference_Div_Last : constant :=  63;
   PLL_Sys_Reference_Div : constant :=  1;

   XOSC_Startup_Delay_Mult_First : constant :=  1;
   XOSC_Startup_Delay_Mult_Last : constant :=  16383;
   XOSC_Startup_Delay_Mult : constant :=  64;

   type Time_Base_Alarm_Kind is (ALARM0, ALARM1, ALARM2, ALARM3);
   Time_Base_Alarm : constant Time_Base_Alarm_Kind := ALARM3;

   type Security_Level_Kind is (Secure, Non_Secure);
   Security_Level : constant Security_Level_Kind := Secure;

   type Board_Kind is (generic_board, rpi_pico2, pimoroni_pico_lipo_2_xl_w, pimoroni_pico_plus_2, pimoroni_plasma_2350, pimoroni_tiny_2350, pimoroni_rp2350_stamp_xl, pimoroni_rp2350_stamp, pimoroni_pga2350, adafruit_feather_rp2350, adafruit_metro_rp2350, adafruit_fruit_jam);
   Board : constant Board_Kind := rpi_pico2;

   PLL_Sys_Post_Div_1_First : constant :=  1;
   PLL_Sys_Post_Div_1_Last : constant :=  7;
   PLL_Sys_Post_Div_1 : constant :=  5;

   type Time_Base_Timer_Kind is (TIMER0, TIMER1);
   Time_Base_Timer : constant Time_Base_Timer_Kind := TIMER0;

   PLL_Sys_Post_Div_2_First : constant :=  1;
   PLL_Sys_Post_Div_2_Last : constant :=  7;
   PLL_Sys_Post_Div_2 : constant :=  2;

end Light_Tasking_Rp2350_Config;
