name = "test_wireless_led"
description = ""
version = "0.1.0-dev"

authors = ["Roger"]
maintainers = ["Roger <rogermc@iinet.net.au>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["test"]

[[depends-on]]
#rp2350_hal = "^1.0"
#light_rp2350 = "^15.2.0"
light_tasking_rp2350 = "^15.2"
embedded_rp2350 = "15.2"
#rp2350_svd = "^1.0"

[configuration.values]
light_tasking_rp2350.Max_CPUs = 2
light_tasking_rp2350.Board = "rpi_pico2"