name = "sketch011blink"
description = ""
version = "0.1.0-dev"

authors = ["Roger"]
maintainers = ["Roger <rogermc@iinet.net.au>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["sketch011blink"]

[[depends-on]]
light_tasking_rp2350 = "*"
#pico_bsp = "^2.2.0"
#light_rp2350 = "^15.2.0"

[[depends-on]]
gnat_arm_elf = "^15"
