
with Ada.Real_Time; use Ada.Real_Time;

with RP2350.IO_BANK0; use RP2350.IO_BANK0;
with RP2350.PADS_BANK0; use RP2350.PADS_BANK0;
with RP2350.SIO; use RP2350.SIO;

package body SVD_Support is

procedure Configure_SIO_With_SVD is
   Next_Time     : Time;
   All_Wifi_Pins : constant := REG_ON_MASK + DATA_MASK + CS_MASK + CLK_MASK;
begin
   -- The SVD defines the 'GPIO' array inside the IO_BANK0 peripheral component.
   -- It breaks down into .GPIO_CTRL.FUNCSEL (or similar name generated by svd2ada). 
   --  keep in mind how the SIO set and clear registers behave:
   --  GPIO_OUT_SET / GPIO_OE_SET only turns on the bits passed as a 1.
   --  Passing 0 changes absolutely nothing.
   --  GPIO_OUT_CLR / GPIO_OE_CLR only turns off the bits passed as a 1.
   --  GPIO_OUT_XOR safely toggles the state of any bit passed as a 1
   --  (perfect for blinking LEDs without reading the register first).

    -- 1. Route the SVD multiplexer
   IO_BANK0_Periph.GPIO23_CTRL.FUNCSEL := SIOB_PROC_23;
   IO_BANK0_Periph.GPIO24_CTRL.FUNCSEL := SIOB_PROC_24;
   IO_BANK0_Periph.GPIO25_CTRL.FUNCSEL := SIOB_PROC_25;
   IO_BANK0_Periph.GPIO29_CTRL.FUNCSEL := SIOB_PROC_29;

   -- 2. Clear out Pad Isolation registers via PADS_BANK0 (Required on RP2350!)
   PADS_BANK0_Periph.GPIO23.ISO := 0;
   PADS_BANK0_Periph.GPIO24.ISO := 0;
   PADS_BANK0_Periph.GPIO25.ISO := 0;
   PADS_BANK0_Periph.GPIO29.ISO := 0;
   
   -- 3. Enable output drivers for all wireless-facing pins
   SIO_Periph.GPIO_OE_SET := All_Wifi_Pins;

   -- 4. Initial state: Force everything LOW to reset the chip
   SIO_Periph.GPIO_OUT_CLR := All_Wifi_Pins;

   -- 5.  Delay ~20ms to allow power regulation on the CYW43439 to discharge
   Next_Time := Clock + Milliseconds (40);
   delay until Next_Time;

   -- 6. Turn ON the power regulator line (REG_ON)
   SIO_Periph.GPIO_OUT_SET := REG_ON_MASK;
   
   -- 7. Delay ~50ms to allow the wireless internal boot ROM to execute
   Next_Time := Clock + Milliseconds (50);
   delay until Next_Time;
  
   -- 8. Drive Chip Select (CS) HIGH to put the SPI bus into idle state
   SIO_Periph.GPIO_OUT_SET := CS_MASK;

end Configure_SIO_With_SVD;

procedure Bit_Bang_Send_Word (Word : UInt32) is
   Next_Time     : Time;
   Current_Bit : UInt32;  
   --  Working pin logic masks
   DATA_MASK : constant UInt32 := 2**24;
   CLK_MASK  : constant UInt32 := 2**29;
begin
   --  Explicitly force GPIO 24 into an Output Mode 
   SIO_Periph.GPIO_OE_SET := DATA_MASK;

   -- Loop through all 32 bits from MSB (bit 31) down to LSB (bit 0)
   for I in reverse 0 .. 31 loop
      --  Isolate the targeted single bit
      Current_Bit := Shift_Right(Word, I) and 1;
      
      --  1. Setup Data Line: Write the single bit value to GPIO 24
      if Current_Bit = 1 then
         SIO_Periph.GPIO_OUT_SET := DATA_MASK;
      else
         SIO_Periph.GPIO_OUT_CLR := DATA_MASK;
      end if;
      
      --  Small pipeline settle delay if running the RP2350 core at full 150MHz
      --  asm volatile ("nop");
      Next_Time := Clock + Milliseconds (50);
      delay until Next_Time;

      -- 2. Pulse the Clock HIGH (Rising Edge - CYW43439 samples the data line)
      SIO_Periph.GPIO_OUT_SET := CLK_MASK;  
      -- Settle delay for SPI Clock High time
      -- asm volatile ("nop");
      Next_Time := Clock + Milliseconds (50);
      delay until Next_Time;

      -- 3. Pull Clock LOW (Falling Edge - Preparing for the next bit step)
      SIO_Periph.GPIO_OUT_CLR := CLK_MASK;
   end loop;

end Bit_Bang_Send_Word;

end SVD_Support;